### ISSUE TITLE
Dogars-chan sometimes reconnect to a previous battle and spasms.

### ISSUE THREAD

**Issue by shoedrip** [shoedrip-unbound/dogars#3]
Cause is unknown.
Many failsafes are in place to prevent this from happening but it still happens.

**Comment by ralex0** [comment]
Hi. Hello. Yes?

Are you still working on this? Is there a repo for dogars-chan too? Can you elaborate on the failsafes? I want to try to improve her.

**Comment by shoedrip** [comment]
Hi, hello.

Dogars-chan was banned from showdown a few months ago. I tried public proxies for a while, but they are unreliable for a bot that needs to be always running. I also have experimenting with using my phone as a proxy, but it turns out showdown requires you to have a week old account and may arbitrarly ban you if one of their mod is bored out of their mind and drops by a champ battle.

Anyway, dogars-chan's code is [here](https://github.com/shoedrip-unbound/dogars/blob/master/src/dogars-chan.ts), she used to be a part of the same program, but she was recently modified to be a client to dogars back-end: the back end notifies clients when a new battle is posted in the current thread, and the client notifies the backend when it needs to take screen captures (through the *snap* command). Communication with the backend currently isn't protected but since I'm mentionning it here I guess I'll have to get to it soon, since it could easily be used for malicious purposes, h-haha.

The failsafe I'm talking about is [here](https://github.com/shoedrip-unbound/dogars/blob/11b1780f7e1315361cb1448402d2b4f05f7b4352/src/Shoedrip/shoedrip.ts#L81), where basically I make sure clients can't be asked to monitor the same battle multiple times by ensuring a monitor request refers to a newer battle than the last that was monitored.
I think this used to be duplicated into many places but the issue probably came from somewhere else, since maybe it never triggered the condition.
Server logs didn't seem to indicate anything unusual.
I haven't been able to reproduce it on my own, and it happens after hours of uptime so I kinda gave up on fixing it, and I don't even think I've seen it happen again since the split.

Honestly the best thing to improve her would be to make her impossible to shut down. An idea would be to find a stable source of working proxies, sanitize proxies (make sure you won't get autobanned for login with one), automatically register accounts and play randomly in a 1v1 meta until she wins once, and finally be able to join showderp battles with any weekold account, while making sure to not leave any trace that could link these accounts together. It'd take time, and I don't know of any "stable source of working proxies", but the rest is technically feasible, I just don't have time for this, so I just maintain dogars when shit breaks, but yeah, I could use some help.

If you want to enhance interaction with other people in chat, you might want to take a look [here](https://github.com/shoedrip-unbound/dogars/tree/master/src/Showdown/BattleHandlers).

Honestly this issue is quite minor ~~compared to the plague that are showdown jannies~~ since it occurs only at the end of a battle when most other have already left for the next one.

Anyway, you're more than welcome to contribute anything, if I don't already have scared you away.
